blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Suggest a new feature or idea
    url: https://github.com/NickColley/semaphore/discussions/categories/new-features-and-ideas
    about: Missing something in Semaphore? Accessibility related features and ideas will be prioritised.
  - name: â” Ask a question
    url: https://fosstodon.org/@semaphore
    about: Send us a toot on Mastodon


